### ISSUE TITLE
Danke schön

### ISSUE THREAD

**Issue by dijoje** [saierd/python-nuclos#1]
Hallo,

wir setzen in unserer Firma auch Nuclos ein. Für eine Genehmigungsseite benötigte ich einen separaten Zugriff. Dies ließ sich hervorragend mit Ihrer API umsetzen (muss mich jetzt an Python 3 gewöhnen, aber das geht schon).

Gute Arbeit !

**Comment by saierd** [comment]
Es freut mich sehr, dass die Bibliothek für Sie nützlich ist.

Bitte melden Sie sich, falls es irgendwelche Probleme oder fehlenden Features gibt. Ich möchte sie gerne weiter verbessern - auch mit Features, an die ich bisher noch nicht gedacht habe, weil ich sie selbst nicht benötige.

**Comment by dijoje** [comment]
Mache ich :+1:

**Comment by dijoje** [comment]
Mache ich :+1:

**Comment by dijoje** [comment]
Hallo Herr Saier,

ein Feature das auch interessant sein könnte, wäre der Datei-Up- und Download.

Gruß Dirk Jende-Holzmann

**Comment by saierd** [comment]
Datei Up- und Download ist in der neuen [Version 1.6](https://github.com/saierd/python-nuclos/releases/tag/1.6) implementiert. Die Dokumentation dazu finden Sie [hier](http://saierd.github.io/python-nuclos/#dokumente).

Leider erst ab Nuclos 4.7, da ich nicht weiß, wie die alte API in diesem Zusammenhang funktioniert.

**Comment by dijoje** [comment]
Toll, ich hoffe ich habe bald Zeit dies zu testen. Wir setzen aktuell die 4.7 ein, also das passt.
Danke

**Comment by dijoje** [comment]
Hallo Herr Saier,
ich konnte endlich den File-Upload testen --> super, funktioniert einwandfrei. :1st_place_medal: 
Ich habe ein Script verwendet, welches ich von Nuclos aus aufrufe, dabei habe ich festgestellt, daß ein absoluter Pfad zur settings.ini notwendig ist. 
Es wäre toll, wenn man direkt Regeln innerhalb von Nuclos mit der Python-API schreiben könnte :-)
Gruß Dirk Jende-Holzmann

**Comment by saierd** [comment]
Der Pfad kann auch relativ zum aktuellen Arbeitsverzeichnis sein. Wie genau haben Sie denn das Script aufgerufen?

**Comment by dijoje** [comment]
Das Python-Script habe ich aus einer Regel ausgeführt:
`Process p = Runtime.getRuntime().exec( "python3 /home/nuclos/script/startreport.py " + ngAuftragsnummer.toString() + " " + strLotnr ); `

**Comment by saierd** [comment]
In dem Fall sollten Sie das Script stattdessen mit

```java
Process p = Runtime.getRuntime().exec("python3 startreport.py " + ngAuftragsnummer.toString() + " " + strLotnr, null, new File("/home/nuclos/script/"));
```

aufrufen und dann relative Pfade im Script verwenden können.

**Comment by dijoje** [comment]
Okay, danke für den Tipp
