### ISSUE TITLE
Nochmal ein Lob

### ISSUE THREAD

**Issue by dijoje** [saierd/python-nuclos#3]
Hallo,
ich habe gerade wieder festgestellt, wie gut und einfach die Python-Nuclos-Api ist, so einfach, dass ich von der Java-Regel-Api ausgehend viel zu kompliziert gedacht habe --> pythonic style

Es wäre wahrlich cool könnte man die Regeln so einfach schreiben, wobei die Java-Api ja schon Vereinfachungen erhalten hat.

Viele Grüße,
Dirk

**Comment by saierd** [comment]
Das freut mich.

Die API Änderungen in 4.28 kannte ich noch gar nicht, die sehen aber sehr sinnvoll aus.

Python hat natürlich trotzdem noch einen Vorteil in Sachen Eleganz. Mit Groovy könnte man eine ähnlich dynamische API aber auch im Java-Land bekommen. Das kostet dann allerdings die statische Typisierung, die man auf dem Server wahrscheinlich lieber haben will.
